apiVersion: v1
kind: Service
metadata:
  name: tak-monitor-svc
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tak-monitor
    app.kubernetes.io/instance: {{ $.Release.Name }}
  ports:
    - port: 8089
      targetPort: 8089
      protocol: TCP
      name: actuators
